GET http://127.0.0.1:8000/vagas/3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvbG9naW4iLCJpYXQiOjE3MTc4ODY2NzAsImV4cCI6MTcxNzg5MDI3MCwibmJmIjoxNzE3ODg2NjcwLCJqdGkiOiJiQVE4cUtBdHZtcnFGSDQ4Iiwic3ViIjoiMTA3IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9._yASAhOmxBVGlpC-xQ0Z6NZvV2HZGA0zTih1C1QsxzA

{}
