POST http://127.0.0.1:8000/vagas
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvbG9naW4iLCJpYXQiOjE3MTczNjU3NDAsImV4cCI6MTcxNzM2OTM0MCwibmJmIjoxNzE3MzY1NzQwLCJqdGkiOiJvUElkRDQ4T29zcUpGWHBqIiwic3ViIjoiMTA3IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.ZIwxFs9WSWo399HULFctM8RDNpWmn3TRE99Nf_a3AAo

{
  "ramo_id": 1,
  "titulo": "Desenvolvedor Front-End",
  "descricao": "Buscamos desenvolvedor front end qualificado blablabla....",
  "competencias": [
    {
      "id": 1,
      "nome": "YourSQL"
    }
  ],
  "experiencia": 2,
  "salario_min": 3400.00,
  "salario_max": 5430.50,
  "ativo": true
}