DELETE http://192.168.1.13:8000/vagas/5
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvbG9naW4iLCJpYXQiOjE3MTczNjU3NDAsImV4cCI6MTcxNzM2OTM0MCwibmJmIjoxNzE3MzY1NzQwLCJqdGkiOiJvUElkRDQ4T29zcUpGWHBqIiwic3ViIjoiMTA3IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.ZIwxFs9WSWo399HULFctM8RDNpWmn3TRE99Nf_a3AAo

{}