GET http://127.0.0.1:8000/vagas
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvbG9naW4iLCJpYXQiOjE3MTc4OTA0NDIsImV4cCI6MTcxNzg5NDA0MiwibmJmIjoxNzE3ODkwNDQyLCJqdGkiOiIxbkhOYXVLYVFpTHFGY2RUIiwic3ViIjoiMTA3IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.30KBT36UC6SCFmk2jbK-Lmu4xzgeETimAoYFmICM9Bk

{}

