GET http://127.0.0.1:8000/vagas
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvbG9naW4iLCJpYXQiOjE3MTkxMDQyNjMsImV4cCI6MTcxOTEwNzg2MywibmJmIjoxNzE5MTA0MjYzLCJqdGkiOiJtSmZiRjRzYXgxanNBUjhsIiwic3ViIjoiMTE0IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.KJJNrDjVe6FLiRIsp2HgOpUvsYpVQeDd8t_e8dG58Tc

{}

