### Listar Usuários Logados
GET http://127.0.0.1:8000/usuarios-logados
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvbG9naW4iLCJpYXQiOjE3MTkxMDIwMzQsImV4cCI6MTcxOTEwNTYzNCwibmJmIjoxNzE5MTAyMDM0LCJqdGkiOiIxeXUwYk9teEtrTktyeG5FIiwic3ViIjoiMTE0IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.SAMSouYyrSnkVWeaj18bCyqUhCu0X1ULvHri1CmCayc
