GET http://127.0.0.1:8000/competencias
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xLjEwOjgwMDAvbG9naW4iLCJpYXQiOjE3MTYxNTkyMzEsImV4cCI6MTcxNjE2MjgzMSwibmJmIjoxNzE2MTU5MjMxLCJqdGkiOiI3RGdmY2FhbnA3YzFyR0lPIiwic3ViIjoiOTgiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.UmlEkDri7OLpm51zx4q4SkT7-W9T4ZqQbdhk0kcMS-Q

{}