GET http://127.0.0.1:8000/api/usuario
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzE0MDg3MTQzLCJleHAiOjE3MTQwOTA3NDMsIm5iZiI6MTcxNDA4NzE0MywianRpIjoiQXpuUENGZXFzQ2h2VzVUSiIsInN1YiI6IjE1IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.bAbJtjtDaYjhADe6Q7yQnl7TJL65Qdh9tDwN2Uon7Bw

{}
//ler dados dp usuario teste

