POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzE0MDg5OTkyLCJleHAiOjE3MTQwOTM1OTIsIm5iZiI6MTcxNDA4OTk5MiwianRpIjoiRzFJckFFelJtdE1Fa0ZLNiIsInN1YiI6IjE1IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.X_IBXRXqHCu4HPL0AckT1eRuQ5k969EAmYiys7cpuGc

{}