DELETE http://127.0.0.1:8000/usuario
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xLjEwOjgwMDAvbG9naW4iLCJpYXQiOjE3MTQ5NTA4MDcsImV4cCI6MTcxNDk1NDQwNywibmJmIjoxNzE0OTUwODA3LCJqdGkiOiJVNUNvOGxaRUE3aXhGdjNiIiwic3ViIjoiNzIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.jBcyebwHrDsBZLPbQpBZeXaTNWZKlhNgQnrwzVxzVhM

{}