GET http://127.0.0.1:8000/usuario
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xLjEwOjgwMDAvbG9naW4iLCJpYXQiOjE3MTU5ODgyODcsImV4cCI6MTcxNTk5MTg4NywibmJmIjoxNzE1OTg4Mjg3LCJqdGkiOiJaR0lIR1hQMFlmMFpQT05jIiwic3ViIjoiOTMiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.QogIgKlnfSOhWGdwGCugOhPG9lccghDuCGy4gFSecLo

{}