POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvbG9naW4iLCJpYXQiOjE3MTQxNzgzODksImV4cCI6MTcxNDE4MTk4OSwibmJmIjoxNzE0MTc4Mzg5LCJqdGkiOiJkSXExZUkwWDR3TmRZQ1VNIiwic3ViIjoiMTkiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.4-404uTSIfCemm81xtaR4DNnGd4gTfrU-ngQ6nQlrOk

{}